### ISSUE TITLE
Programs window is not responding for 2 or 3 seconds on first open

### ISSUE THREAD

**Issue by fifaplayer88** [tnodir/fort#213] opened 2024-02-13 02:41 UTC
After I reboot my PC and open the FortFirewall (Programs) window, when I try to click or select any Application, I noticed that the window become laggy and not responding for seconds, after that it becomes normal. this always happen after reboot or start FortFirewall for first time.

**Comment by fifaplayer88** [comment] 2024-02-13 08:28
System information
Window11 23H2 22631.3085
SW:FortFirewall-3.11.4-windows10-x86_64
Monitored 4K

**Comment by tnodir** [comment] 2024-02-13 10:46
Duplicate of #49

**Closed by tnodir** 2024-02-13 10:46 UTC
