### ISSUE TITLE
BSOD updating to v3.6.2 (.4)

### ISSUE THREAD

**Issue by bluelayer** [tnodir/fort#44] opened 2023-01-11 12:47 UTC
hi!

just got one bsod when updating to 3.6.2
![IMG_20230111_121250](https://user-images.githubusercontent.com/3768436/211809974-79ac4c80-89de-4ba4-ac68-6db8e18d623a.jpg)

**Comment by tnodir** [comment] 2023-01-11 13:00
The fix for #41 was not ideal :(
v3.6.1 can BSOD when updating to v3.6.2

I've fixed it in v3.6.2

**Comment by bluelayer** [comment] 2023-01-11 13:28
fixed in 3.6.2.....3?

**Comment by tnodir** [comment] 2023-01-11 13:33
Yes, it should not crash when updating from 3.6.2 to 3.6.3 and later.

**Comment by tnodir** [comment] 2023-01-11 13:38
Workaround to not crash when updating from 3.6.1 to 3.6.2 is:
- close all programs
- turn off the Internet connection (Ethernet adapter or WiFi)
- install v3.6.2

**Comment by bluelayer** [comment] 2023-01-11 18:22
> Workaround to not crash when updating from 3.6.1 to 3.6.2 is:
> 
>     * close all programs
> 
>     * turn off the Internet connection (Ethernet adapter or WiFi)
> 
>     * install v3.6.2

that's what i was looking for =)

**Comment by tnodir** [comment] 2023-01-13 08:36
@bluelayer Please check the update to [v3.6.3](https://github.com/tnodir/fort/releases/tag/v3.6.3).

**Comment by bluelayer** [comment] 2023-01-16 20:19
> @bluelayer Please check the updating from v3.6.2 to [v3.6.3](https://github.com/tnodir/fort/releases/tag/v3.6.3).

perfect! 

thank you!

**Comment by bluelayer** [comment] 2023-01-18 00:13
updating from v3.6.3 to v3.6.4... puff

**Comment by tnodir** [comment] 2023-01-18 04:20
@bluelayer Please send [memory dump](https://www.windowscentral.com/how-open-and-analyze-dump-error-files-windows-10) to nodir.temir@gmail.com

**Comment by tnodir** [comment] 2023-01-18 10:01
@bluelayer I can't reproduce the BSOD..
- what is your OS version?
- which fort version do you install: `FortFirewall-3.6.4-windows-x86.exe` or `FortFirewall-3.6.4-windows10-x86_64.exe`?
- what programs (with Internet connection) are running during the update?

**Comment by bluelayer** [comment] 2023-01-18 12:45
> @bluelayer I can't reproduce the BSOD..
> 
>     * what is your OS version?
> 
>     * which fort version do you install: `FortFirewall-3.6.4-windows-x86.exe` or `FortFirewall-3.6.4-windows10-x86_64.exe`?
> 
>     * what programs (with Internet connection) are running during the update?

win 11 22621.1105

64b

anydesk and a cloud client

I normally don't have pagefile activated, so, no dump.
today I activated it and made the update to 3.6.4 and no problem this time.......
then updated to 3.6.5.... ok too.

**Comment by tnodir** [comment] 2023-01-18 13:24
> today I activated it and made the update to 3.6.4 and no problem this time.......
> then updated to 3.6.5.... ok too.

There was a race condition bug with running connections on driver closing.
I hope that I fixed it finally...

Please try to reproduce the crash by updating 3.6.5 to 3.6.5 (yes, to itself) on heavy loaded system with many Internet connections. Thanks.

**Comment by bluelayer** [comment] 2023-01-18 19:46
> Please try to reproduce the crash by updating 3.6.5 to 3.6.5 (yes, to itself) on heavy loaded system with many Internet connections. Thanks.

seems ok

**Closed** 2023-01-25 12:19 UTC
Labels: bug
